# Download and install: 
# https://www.docker.com/products/docker-desktop/
# run docker-compose up from the terminal
# ctrl-c to exit

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - '4000:4000'